# Generated by Django 4.1.6 on 2023-02-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeOfWorkout', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
