# Generated by Django 4.1.6 on 2023-02-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_plan_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='exercises',
        ),
    ]
