# Generated by Django 4.1.6 on 2023-02-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_plan_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='exercises',
            field=models.ManyToManyField(to='main_app.exercise'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.plan')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
