# Generated by Django 4.1.6 on 2023-02-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_plan_user'),
        ('main_app', '0007_remove_comment_plan_comment_exercise'),
    ]

    operations = [
    ]
