# Generated by Django 4.1.6 on 2023-02-15 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.meal'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.exercise'),
        ),
    ]
