# Generated by Django 4.1.6 on 2023-02-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_body_comment_content'),
        ('main_app', '0014_comment_meal_alter_comment_exercise'),
    ]

    operations = [
    ]
